function C = getControls(this)
%getControls Get the controls description string

C = [ ...
    '----- CONTROLS ---------------------------' newline ...
    newline ...
    'VIEW' newline ...
    '  Toggle zoom [z]' newline ...
    '  Toggle fragments view [F]' newline ...
    '  Toggle trajectories view [T]' newline ...
    '  Toggle quarantine view [Q]' newline ...
    newline ...
    'NAVIGATION' newline ...
    '  Play/pause [space]' newline ...
    '  Flashback and play [b]' newline ...
    '  Flashback duration [d...]   ' num2str(this.Visu.fbd) ' frames' newline ...
    '  ±1 frame [' char(8592) ',' char(8594) '] (on pause)' newline ...
    '  Rewind [Page down]' newline ...
    newline ...
    'FRAGMENTS' newline ...
    '  Highlight [Middle click]' newline ...
    '  First unused [Page up]' newline ...
    '  Cut [c] (at t-1)' newline ...
    '  Toggle quarantine status [q]' newline ...
    '  Save [s]' newline ...
    newline ...
    'TRAJECTORIES' newline ...
    '  Select trajectory [Left click]' newline ...
    '  Search trajectory [r...]' newline ...
    '  New trajectory [t]' newline ...
    '  Include fragment [+]' newline ...
    '  Remove fragment [-]', newline ...
    '  End [' char(8593) ']' newline ...
    '  Beginning [' char(8595) ']' newline ...
    '  Flashback last fragment and play [f]' newline ...
    '  Export [S]'];
