function C = getControls(this)
%getControls Get the controls description string

C = [ ...
    '----- CONTROLS ---------------------------' newline ...
    newline ...
    'NAVIGATION' newline ...
    '  Play/pause [space]' newline ...
    '  ±1 frame [' char(8592) ',' char(8594) '] (on pause)' newline ...
    '  Rewind [Page down]'];
