function C = getControls(this)
%getControls Get the controls description string

C = [ ...
    '----- CONTROLS ---------------------------' newline ...
    newline ...
    'NAVIGATION' newline ...
    '  Play/pause [space]' newline ...
    '  ±1 frame [' char(8592) ',' char(8594) ']' newline ...
    '  Next frame [right click]' newline ...
    '  Rewind [Page down]' newline ...
    '  Zoom [z]' newline ...
    '  Update [u]' newline ...
    '  Update all [U]' newline ...
    '  Save [s]' newline ...
    newline ...
    'SHAPES' newline ...
    '  Split [c]' newline ...
    '  Merge [m]' newline ...
    '  Delete [Del]' newline ...
    '  First free shape [Page up]' newline ...
    newline ...
    'CELLS' newline ...
    '  Soma [n]' newline ...
    '  Centrosome [j]' newline ...
    '  Cone [k]', newline ...
    '  Undefined part [,]', newline ...
    '  End of cell [Return / middle click]' newline ...
    '  Cell to shapes [f]' newline ...
    '  Shapes on frame to somas [a]' newline ...
    '  All shapes to somas [A]'];
